# Generated by Django 4.1.3 on 2022-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер по порядку')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=25, verbose_name='Категория')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
